title: Maryam NouriAiin
logo: /assets/img/tini_headshot.png
description: Welcome to my GitHub repository/portfolio for the Computational Biology course! 

show_downloads: false
theme: jekyll-theme-minimal
