title: Maryam NouriAiin
logo: /assets/img/Tini.jpeg
description: Welcome to my GitHub repository/portfolio for the Computational Biology course! 

show_downloads: false
theme: jekyll-theme-minimal
body {
    background-color: #add8e6; /* Light blue background */
}
