title: Maryam NouriAiin
logo: /assets/img/Tini_headshot.jpg
description: Welcome to my GitHub repository/portfolio for the Computational Biology course! 

show_downloads: false
theme: jekyll-theme-minimal
